var questions = {
    curr: 1,
    length: 5,
    1: {
        Q: "lorem1?",
        opt1: "opt1",
        opt2: "opt2",
        opt3: "opt3",
        opt4: "opt4",
        ans: "1",
        chosen: "",
    },
    2: {
        Q: "lorem2?",
        opt1: "opt1",
        opt2: "opt2",
        opt3: "opt3",
        opt4: "opt4",
        ans: "1",
        chosen: "",
    },
    3: {
        Q: "lorem3?",
        opt1: "opt1",
        opt2: "opt2",
        opt3: "opt3",
        opt4: "opt4",
        ans: "1",
        chosen: "",
    },
    4: {
        Q: "lorem4?",
        opt1: "opt1",
        opt2: "opt2",
        opt3: "opt3",
        opt4: "opt4",
        ans: "1",
        chosen: "",
    },
    5: {
        Q: "lorem5",
        opt1: "opt1",
        opt2: "opt2",
        opt3: "opt3",
        opt4: "opt4",
        ans: "1",
        chosen: "",
    },
    6: {
        Q: "lorem6",
        opt1: "opt1",
        opt2: "opt2",
        opt3: "opt3",
        opt4: "opt4",
        ans: "1",
        chosen: "",
    },
}

module.exports = { questions };